// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("../src/Demo.bs.js");
var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");

Jest.describe("Demo", (function (param) {
        return Jest.test("doubleSum 2 inputs", (function (param) {
                      return Jest.Expect.toEqual(Jest.Expect.expect(Demo.doubleSum(2, 5)), 14);
                    }));
      }));

/*  Not a pure module */
